//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coin
    {
        public int CoinID { get; set; }
        public string OriginCountry { get; set; }
        public Nullable<int> YearMinted { get; set; }
        public string CoinMaterial { get; set; }
        public string CoinValue { get; set; }
    }
}
