//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonCoin
    {
        public int PersonCoinID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> CoinID { get; set; }
    }
}
