//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialCoin
    {
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> Year { get; set; }
        public string Type { get; set; }
        public string Issuing_country { get; set; }
        public string Provenance { get; set; }
        public string Firm { get; set; }
        public Nullable<System.DateTime> Date_of_sale { get; set; }
        public int SpecialCoinID { get; set; }
    }
}
